# Generated by Django 4.1.7 on 2023-04-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='no-user.png', null=True, upload_to='profile_pic'),
        ),
    ]
