# Generated by Django 4.1.7 on 2023-04-06 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile'),
        ),
    ]
