# Generated by Django 4.1.7 on 2023-04-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_friend_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='profile',
        ),
        migrations.AddField(
            model_name='friend',
            name='profile',
            field=models.ManyToManyField(related_name='friends', to='User.friend'),
        ),
    ]
