# Generated by Django 4.1.7 on 2023-04-21 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_friend_profile_friend_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='profile',
        ),
        migrations.AddField(
            model_name='friend',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='User.profile',unique=False),
            preserve_default=False,
        ),
    ]
