# Generated by Django 4.1.7 on 2023-04-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_friend_profile_friend_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile'),
        ),
    ]
